### ISSUE TITLE
Move AWS provider into its own plugin repo

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1022]
With the recent work we have been doing to introduce plugin support for CodeOnTap combined with the testing work being done by @RossMurr4y in https://github.com/codeontap/gen3-azure we should now be ready to move the AWS provider out to its own repository to align it with the plugin concept. 

This ticket would be to move the https://github.com/codeontap/gen3/tree/master/providers/aws directory into its own repository

**Comment by roleyfoley** [comment]
Discussed the plan 

- create a new repository in the organisation 
- Push the existing codeontap/gen3 repo into this repository 
- Submit a PR removing the non AWS specific parts from the repo 
- Submit a PR in the existing codeontap/gen3 repo removing the aws specific parts

**Comment by ml019** [comment]
Closing - now in separate hamlet repo - https://github.com/hamlet-io/engine-plugin-aws
