### ISSUE TITLE
Tagging Support: SNS Topics 

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1131]
Add tagging support for the following resources - including the generation of an appropriate name

- AWS::SNS::Topic

**Comment by ken9ross** [comment]
@roleyfoley can you point me at how to trigger the creation of an SNS::Topic?

**Comment by roleyfoley** [comment]
The topic component https://docs.hamlet.io/reference?type=component&instance=topic is the one you want.
