### ISSUE TITLE
Deployment Groups

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1196]
Deployment groups provide the ability to orchestrate the provisioning of components in a solution. They are essentially the replacement of levels and allow for the implicit ordering defined via the manageEnvironment Jenkins jobs to be defined in our CMDB configuration explicitly with the ability to have fine grain control over the provisioning ordering of components

Ordering is defined by each group rather than an explicit list, each group specifies another that it follows along with an configuration option on whether this must always happen. 

This order is processed through the unitlist deployment level added in #1149 which will output the full deployment group order list including the deployment units which belong to each group. 

The execution engine uses this along with command line options it has been provided ( i.e. a specific group or unit ) to execute both template generation and deployment in the provided order 

The execution engine should follow rules when using the unit list to manage deployment units 
- A Deployment group command line option of  `_all` should run generation for units in the list
- A command line option specifying a group should run the generation for that group and also generate any templates for groups specified as always preceding this group 
- If only a dpeloyment unit is specified just the unit should be generated 

Along with controlling ordering of deployments, deployment groups also provide the ability to define a component type qualifier, which essentially incorporates the existing level setup and state routines, A group can have a defined level which is used to generate templates used at different levels of deployment 

Groups can also be nominated as subset groups which is used to control where subset resources are created. This is to accommodate large deployments where the existing subset structure based on levels creates templates which are unsupported by providers ( i.e. AWS stack output limit )

**Comment by ml019** [comment]
@roleyfoley not quite sure what you mant by "component type qualifier, which essentially incorporates the existing level setup and state routines" - mainly in relation to state routines. Is the qualifier the equivalent of the current "subset" concept?

**Comment by roleyfoley** [comment]
Done
