### ISSUE TITLE
Architecture - Engine and Executor 

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1231]
This issue is to introduce an architectural idea to clearly define the different functions performed in how codeontap works 

At the moment we have a tight coupling between our bash based scripts and the freemarker template generation engine. With the introduction of the python based cli tool ( https://github.com/codeontap/gen3-cli ) this causes issues in how we can integrate the CLI into codeontap. At the moment we have wrapped the existing bash scripts in python based code. While python is OS independent, bash isn't easily OS independent and also doesn't have a packagement process ( outside of the OS). This isn't ideal.

This process has highlighted two distinct parts of the codeontap gen3 function ( in this repo) :

- **Generation process** This side of codeontap is responsible for generating the files ( CFN templates, bash scripts, config files ) that are required to perform a deployment. This process is provided through our freemarker engine and the CMDB 
- **Execution process**. This side is responsible for implementing the deployment defined in the template generation process. This process is provided through our bash based scripts ( see manageStack.sh manageDeployment.sh etc. 

At the moment there is quite tight coupling between these two process with the generation process creating bash based scripts that are run directly by the execution process. This ties directly in with the issue we have with the python CLI 

Instead of directly generating the scripts that are executed by the execution engine we should establish an agreed contract between the generation and execution processes

**Comment by roleyfoley** [comment]
The proposal here is to make the contract between the generation and the execution process Plans. 

Plans are generated by the generation process and outline the tasks required to complete a given task. 

At the moment we have 2 tasks:
- Generation - This outlines the documents which need to be created by a call to createTemplate. Currently this actually has a plan, however this is implemented as a bash output file which locks it into a bash based execution process
- Deployment - Implementing the deployment of a component based on the documents created by the Generation task. The plan for this is currently implemented in the code of manageStack or manageDeployment.

With the introduction of plans we would have a standard format for both of these tasks. The plan would outline each piece of work required to perform the task along with the parameters required to do this. The plan would be in a standard data model ( JSON ) and outline standard work item names which the execution process is responsible for implementing. 

The work items in the plan should have no knowledge of the execution process which will run the plan,  this separation allows for mobility beween the generation and the execution process with the potential to have multiple execution runners ( e.g. a python cli execution process, and a powershell module ). Both of the execution runners would receive the same plan but they would have individual implementations of the work items. As long as they all achieve the same result, we are happy.

**Comment by ml019** [comment]
Forthwith, The term "Plan" is to be replaced with "Contract". We will use this term ging forward and refactor gen3 accordingly.

**Comment by ml019** [comment]
Move content to Hamlet Enhancement Proposal

**Comment by roleyfoley** [comment]
Done as ADR001
