### ISSUE TITLE
Support additional encryption prefix

### ISSUE THREAD

**Issue by kshychko** [hamlet-io/engine#1252]
In order to make clear that the a string was encrypted with AWS KMS we should support additional prefix for encrypted strings:
`kms+base64:` or just `kms:`

**Comment by roleyfoley** [comment]
This should already be supported. When defining credentials or settings the user can choose to use a prefix or not

When it comes to components the only component with a defined encrypted value is the database. 

For the database the prefix provided via the attributes is controlled in the following solution configuration on the db component 

```
            {
                "Names" : "GenerateCredentials",
                "Children" : [
                    {
                        "Names" : "Enabled",
                        "Type" : BOOLEAN_TYPE,
                        "Default" : false
                    },
                    {
                        "Names" : "MasterUserName",
                        "Type" : STRING_TYPE,
                        "Default" : "root"
                    },
                    {
                        "Names" : "CharacterLength",
                        "Type" : NUMBER_TYPE,
                        "Default" : 20
                    },
                    {
                        "Names" : "EncryptionScheme",
                        "Type" : STRING_TYPE,
                        "Values" : ["base64"],
                        "Default" : ""
                    }
                ]
            },
```

**Comment by roleyfoley** [comment]
which I just noticed only allows certain values 🤦‍♂ 

Will have to add more properties to the values section

**Comment by roleyfoley** [comment]
Encryption scheme values have now been removed which allows for any scheme to be set
