### ISSUE TITLE
Embed framework version in template generation/promotion

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#129]
While we check acceptance of build commits when promoting code, we don't confirm that the lower environment was generated using the same version of the framework about to be used in the higher environment. This can allow issues to slip through when frameworks are upgraded.

In order to mitigate this,

* include the generation framework version in the metadata of all templates
* when promoting, ensure that all the templates in the lower environment were built with the version of the framework about to be used in the higher environment

**Comment by roleyfoley** [comment]
Implemented in https://github.com/hamlet-io/engine/pull/1469

**Comment by roleyfoley** [comment]
Done
