### ISSUE TITLE
Move all of adaptor to shared provider

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1293]
## Expected Behaviour
The adaptor provider should work as part of the shared provider not 

## Current Behavior
With the implementation of #1292 the generation plan didn't pick up the appropriate subsets to create the templates that were required. Moving state and setup to the aws provider got it going

**Comment by RossMurr4y** [comment]
@roleyfoley is this ticket complete? I have a ticket i want to raise for the Adaptor component but it depends on whether its still "in-progress" or not.

**Comment by roleyfoley** [comment]
Yeah lets close this following our chat the other day the adaptor isn't generic and should be per provider. each registry provider would implement this essentially.
