### ISSUE TITLE
Bug - Name-space Provider Attributes

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine#1441]
## Expected Behavior

When adding new attributes to a component within a provider, the name-spacing should occur only at the first level of the attribute structure that is not present in the shared provider.

## Current Behavior

Attributes that are added as top-level attributes work as expected, however adding new children to an existing attribute will replace the top-level attribute.

### Example

The shared provider defines the following top-level attribute `AccessLogging` on the `apigateway` component, with a single child-attribute of `Enbabled`.

```json
            {
                "Names" : "AccessLogging",
                "Children" : [
                    {
                        "Names" : "Enabled",
                        "Description" : "Logging of the API Gateway Access Logs.",
                        "Type" : BOOLEAN_TYPE,
                        "Default" : true
                    }
                ]
            }
```

In the AWS provider, adding new children like so will result in an attribute of `aws:AccessLogging` and not `AccessLogging` with children of `aws:DestinationLink`, `aws:KinesisFirehose` and `aws:KeepLogGroup`

```json
        {
            "Names" : "AccessLogging",
            "Children" : [
                {
                    "Names" : "DestinationLink",
                    "Description" : "Destination for the Access logs. If not provided but AccessLogging is enabled, Access logs will be sent to CloudWatch.",
                    "Children" : linkChildrenConfiguration
                },
                {
                    "Names" : "KinesisFirehose",
                    "Description" : "Send Access logs to a KinesisFirehose. By default, the Firehose destination is the OpsData DataBucket, but can be overwritten by specifying a DestinationLink.",
                    "Type" : BOOLEAN_TYPE,
                    "Default" : false
                },
                {
                    "Names" : "KeepLogGroup",
                    "Description" : "Prevent the destruction of existing LogGroups when enabling KinesisFirehose.",
                    "Type" : BOOLEAN_TYPE,
                    "Default" : true
                }
            ]
        }
```

Current workaround is when adding these new attributes on the provider, to manually add the namespaces and on the macro `addResourceGroupInformation` to set `prefixed=false` - but this isn't ideal as its not enforced.

## Context

Adding new attributes in a provider, has meant I've had to manually namespace the attributes in the definition for now.

**Comment by roleyfoley** [comment]
@RossMurr4y Is this still an issue? please review and icebox or close if we have a workaround

**Comment by RossMurr4y** [comment]
Presently this has been partially resolved, and a workaround exists.

- the top-level attribute ("AccessLogging" in the example) no longer receives the unnecessary prefix.
- the children however, do not receive a prefix at all. This was proving particularly involved to resolved, so temporary workaround was to manually prefix them within the provider that has added them.

i.e this is the definition in the AWS provider that adds 3 new children to `AccessLogging`:

```json
        {
            "Names" : "AccessLogging",
            "Children" : [
                {
                    "Names" : "aws:DestinationLink",
                    "Description" : "Destination for the Access logs. If not provided but AccessLogging is enabled, Access logs will be sent to CloudWatch.",
                    "AttributeSet" : LINK_ATTRIBUTESET_TYPE
                },
                {
                    "Names" : "aws:KinesisFirehose",
                    "Description" : "Send Access logs to a KinesisFirehose. By default, the Firehose destination is the OpsData DataBucket, but can be overwritten by specifying a DestinationLink.",
                    "Types" : BOOLEAN_TYPE,
                    "Default" : false
                },
                {
                    "Names" : "aws:KeepLogGroup",
                    "Description" : "Prevent the destruction of existing LogGroups when enabling KinesisFirehose.",
                    "Types" : BOOLEAN_TYPE,
                    "Default" : true
                }
            ]
        }
```

Closing, as we have a valid workaround for now. New ticket to be created for any future work on this as the requirements have changed.
