### ISSUE TITLE
Provider loading through the blueprint

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1447]
## Current Behaviour
To use multiple providers you need to currently specify the providers you want to use the command line when running a template generation. As a result you need to know which providers are required for a given product and for a specific purpose

## Expected Behaviour
You can define the providers that you want to use in your blueprint and the bootstrap process will load the providers you provide during the bootstrap process

## Possible Solution
- Similar to scenarios include the ability to list a collection of providers and their sources at the Tenant or Product level of a blueprint. These will be included in the providers list which has been provided on the command line 
- Using this information we should also be able to generate a script similar to the one used in [docker-hamlet](https://github.com/hamlet-io/docker-hamlet/blob/master/config.json) image which can be used by an executor to download and configure the appropriate providers for a template pass 

## Context
This would provide control to users to define which providers they want to use and to also specify the versions of a given provider that they would like to use.

**Comment by RossMurr4y** [comment]
I think your suggestion of combining the modules/scenarios and provider loading makes complete sense. This would allow us to consolidate the concepts of `modules` and `plugins` - a "provider plugin" as we currently implement them could instead become a `module` that implements another provider, but the way they are loaded and discovered can be shared. This would make the contribution process a lot clearer too because whether you're just looking to add a new entrance, or an entirely new cloud provider, the process to make it available to the engine (and other users) is the same.

**Comment by roleyfoley** [comment]
> I think your suggestion of combining the modules/scenarios and provider loading makes complete sense. This would allow us to consolidate the concepts of `modules` and `plugins` - a "provider plugin" as we currently implement them could instead become a `module` that implements another provider, but the way they are loaded and discovered can be shared. This would make the contribution process a lot clearer too because whether you're just looking to add a new entrance, or an entirely new cloud provider, the process to make it available to the engine (and other users) is the same.

I don't think we can merge `modules` and `plugins` - a plugin is more of the packaging of a provider ( i.e. the plugin is a git repo that can contain one or mode providers ) the providers in turn have the ability to offer various features to the hamlet engine, components, referencedata, services and modules would be one of the features that are offered.

**Comment by roleyfoley** [comment]
A module is only concerned with injecting input data, it doesn't implement anything new by itself

**Comment by RossMurr4y** [comment]
That would make it consistent with other uses of the word `modules` I suppose. I was just thinking of consolidation of the way different parts of hamlet are distributed and downloaded as needed. Sounds like they both have their place.

**Comment by roleyfoley** [comment]
Completed
