### ISSUE TITLE
Composite Object extra parameter detection

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1450]
## Expected Behaviour
If an object that is passed to the composite object processing has more parameters than expected an error should be provided to the user outlining the extra parameters 

## Current Behaviour
The extra parameters are stripped from the object without knowledge

## Possible Solution
During the getCompositeObject function call check for parameters which haven't been defined in the configuration schema 

## Context
This is useful for a couple of purposes 
- Provides better feedback to users when they are working in a CMDB 
- Allows us to catch configuration migrations which might have been missed when implementing a schema on a configuration item

**Comment by RossMurr4y** [comment]
Rather than simply check for unspecified attributes, would it be of value to update the JSONSchema to define `additionalProperties` keyword, and then validate against the schemas? This should allow for validation against an older schema, whereas I think a freemarker implementation would only check against the latest definition for a solution?

**Comment by roleyfoley** [comment]
Adding support for detecting the extra values would allow us to choose when to add the additionalProperties json schema parameter. The main concern here was to address potential issues in #1448 where I might have missed parameters that were unexpected. We are mostly at the end of data leaking directly from the blueprint to usage within the engine, but its still a risk

**Comment by RossMurr4y** [comment]
So would this essentially be its own metaparameter that is the Hamlet engine equivalent of `additionalProperties`?
