### ISSUE TITLE
Artefact Handling for Application Components

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine#1486]
## Expected Behaviour

Components that make use of a code artefact should be able to have it pulled in from an external source.

## Current Behaviour

#1453 updates the Lambda component with this capability. This capability should be available to all components using an external image.

## Possible Solution

- [x] standardise the use of the source-loading configuration from #1453 so it can be re-used across components
* add this capability to the following components:
  - [x] apigateway
  - [x] spa
  - [x] ecs
  - [x] containertask
  - [x] computecluster
  - [x] containerservice
  - [x] adaptor 
  - [x] mobileapp 
  - [x] contentnode 
  - [x] datapipeline
  - [x] dataset - when using s3 
  - [x] template

## Context

Standardise the way that external images are loaded into a CMDB

**Comment by RossMurr4y** [comment]
@roleyfoley have I missed any of the components that make use of code artefacts? Probably have.

Depending on how far you want to go with this idea, this could potentially be used for bootstrapping scripts of virtual machines as well. But thats a bit beyond the scope of this ticket.

**Comment by roleyfoley** [comment]
A search for `BUILD_FORMATS` across the code ( which is what sets the registry ) and getBuildScript ( the registry sync function ) 

- [ ] adaptor 
- [ ] mobileapp 
- [ ] contentnode 
- [ ] datapipeline
- [ ] dataset - when using s3 
- [ ] template

**Comment by roleyfoley** [comment]
Adding support for explicit AMI id and the ability to use parameter store values for image sources would be handy ( very AWS thing though so will be namespaced options )

**Comment by roleyfoley** [comment]
That is now all of the image components updated in the core and AWS providers. Its been a good thing to review as its show points where we can actually disable the image completely and use extensions to make some really powerful tools. 

I think we can call this closed now
