### ISSUE TITLE
Message Transfer Agent Component

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#1499]
## Expected Behaviour
A common requirement for solutions is to permit inbound and outbound emails. 

It should be possible to include email configuration in the solution and leverage link processing to reduce the amount of manual configuration required.

## Current Behaviour
To date, configuration for these has been done as a mixture of manual configuration and permissions configuration via extension files.

## Possible Solution
Introduce a new component - the Message Transfer Agent - MTA. 

An MTA will deal with a specific domain. If multiple domains are required, multiple MTA instances will be configured.

The MTA component will expose the attributes that other components needs to send emails, such as relay endpoints. 

An MTA will support an MTA Rule subcomponent. Rules control the behaviour of the MTA. Rules will have the following attributes;
- Direction - inbound/outbound
- Action - (within a direction) forward/drop
- Priority - controls order within a direction in which rules are applied.
- Filters - recipient, source IP Addresses
- Links - will relate to the action. For instance, an action of forward with a link to an S3 bucket would create a rule to save inbound emails in S3.

Rules will be processed in priority order with the option for an action to indicate whether or not processing should be terminated as a result of the action being undertaken. An example of this would be an action of "drop" which would cease processing of the email. 

Inbound link processing on other components will need to be added, for example permission for SES to write to an S3 bucket, permission for SES to access the KMS key for S3.

Outbound link processing on components that can send emails, such as containers or functions, will need to be added. This should replace use of permissions macros in component extension files.

## Context
Email support is a common enough requirement for solutions that it is worthwhile investing in more fully supporting it in hamlet.

**Comment by roleyfoley** [comment]
Support added to the shared provider and implemented using AWS SES
