### ISSUE TITLE
[BUG] Storage Replication and impact on Deployment Priority

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine#1526]
## Expected Behaviour

I can define two `storage` components in my solution, one as a `replicasource` role and the other as `replicadestination`, and the Hamlet Engine handles their prioritisation for me.

## Current Behaviour

The default value for `deployment:Priority` on the ResourceSet is used which is the same for each component and so they are seen as equal and which will occur first is not clear (and may not be consistent either). The implied dependancy of a "replica" of something is not factored in. 

## Possible Solution

* Implement unique processing of the `deployment:Priority` attribute within the creation of a Solution that evaluates a links role and, where a replicasource/replicadestination match is found, ensure the source has a priority that would see it created/removed first.

* (alternative) Provide feedback to the user that they are attempting to generate a template for the Source when the Destination does not yet exist (so cannot create the source).

**Comment by roleyfoley** [comment]
The resourceset priority is only used during the resourceset generation and for standard generation the deployment:Priority is used 

Are you saying that when processing resource sets we should honour each units deployment:Priority? 

What's the actual error here that is being received?

**Comment by roleyfoley** [comment]
Main concern here is around providing feedback to user on the replication process and providing details on the order required for replication to work

**Comment by roleyfoley** [comment]
Also need to account for the baseline replicating, if the destination doesn't exist we need to warn the user they need to run baseline again once the destination has been created

**Comment by RossMurr4y** [comment]
I have updated the original description with an alternative solution of simply providing feedback. This was discussed during review or backlog tickets as a measure that would provide immediate results. There are significant hurdles to overcome when it comes to determining the prioritisation of two resources in this scenario so providing user feedback seems the optimal outcome at this time.

**Comment by roleyfoley** [comment]
Having tested this with a deployment now I think we can call this closed. I attempted to deploy the destination before the source and received an exception that it wasn't deployed. Then updated the deployment prirotiy of the replica destination and could deploy the component.
