### ISSUE TITLE
[BUG] Link processing failing for API Gateway publishers

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#1544]
## Expected Behaviour
Multiple links can be defined under a `Links` attribute

## Current Behaviour
Link attributes are expected directly under the `Links` attribute

## Possible Solution
Reinstate the `Subobjects : true` attribute in the component configuration.

A scan of the engine repo suggests the baseline and lb components have the same issue.

## Steps to Reproduce
1.  Select a project with publication of api gateway specifications
2. Attempt to generate the template 
3.
4.

## Your Environment
* CMDB Version used: 
* Blueprint:

**Comment by roleyfoley** [comment]
Are you saying that the attribute set is based on Subobjects : true? 
I think that might be ore the hub. In some cases you can really only have one link. So making two available is confusing.
