### ISSUE TITLE
Add Maintenance Window configuration to RDS instances

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#159]
Maintenance windows for RDS define when minor work can be scheduled and performed by AWS. 
By default the maintenance window is set by AWS and can be different for each RDS instance. So that we can report and identify maintenance windows from the template configuration we should set the window using the PreferredMaintenanceWindow parameter. 

Since maintenance windows can be used on other services, we should have a codeontap maintenance window configuration which staggers across the environments, segments and tiers. 

- Environments: staggered across days of the week
- Segments: staggered across half day of the environment day (morning/night) 
- Tiers: staggered by the hour of the segment half day 

This way updates are applied on a predictable, rolling basis.

**Comment by roleyfoley** [comment]
@ml019  Thoughts? 
Not sure if this is too complicated for what we would want, but this is the maintenance window configuration I was thinking of defaulting to for the SSM components as well.

**Comment by ken9ross** [comment]
Regarding the RDS maintenance windows
Current state is:
- aws:RDS will be updated on a random day at a random 30 minute block starting time in the range 12:00–20:00 UTC (if in ap-southeast-2)
- azure:RDS will be updated any day 1700-0800 local time
- aws:QueueHost already has a MaintenanceWindow defined (which while not the correct format for RDS, can be translated so I think should be used as is as a structure to be consistent)

In the case of an Aurora cluster, for the cluster, with each DB instance being scheduled for 1 hour thereafter. If not set it would use the current AWS default as per above.
In the case of azure:RDS will only make use of the day as there are only two options (other than default) Mon-Thu 1700-0800 or Fri 1700-0800 local time
This is not what you were asking for in the ticket, but I don't understand your objective with the segment and tier being included in the calculation of the timewindows

BTW The current default for QueueHost is Sunday 1000AEST, is that intended?

**Comment by roleyfoley** [comment]
So having looked at this again ( 3 years down the track ) I think what was suggested is too complicated for implementation within hamlet. 

We should ensure that components that have maintenance windows can be configured in a standard way. Users can then use deployment profiles to develop their own scheduling processes 

So I think requirements here are 

- Times set in UTC across the board 
- Determine a common pattern to use for scheduling inline with what the providers offer. If this isn't the case we should make a broader configuration pattern within hamlet to define schedules which would give us the ability transform this into the appropriate formats the providers require.

**Comment by roleyfoley** [comment]
So I think we could merge this into an epic around maintenance window for managed IaaS services 

- db 
- queue 
- queuehost

**Comment by ken9ross** [comment]
The current structure is
```
"MaintenanceWindow" : {
   "DayOfTheWeek" : "Friday",
   "TimeOfDay" : "16:00",
    "TimeZone" : "UTC"
}
```
I have a process (not yet converted to a standard function) which converts the TimeZone for RDS to the required UTC. Just found out that while queuehost supports TimeZone, it doesn't recognise AEST (hence need to convert to standard function)

Can you point me at information about `queue`
