### ISSUE TITLE
[BUG] Loader entrance loading modules on execution 

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1615]
## Current Behaviour

When running hamlet setup ( which invokes the loader entrance ) the input processing is trying to load the modules found in the layers. If you are trying to update a plugin which contains fixes for breaking engine changes the loader fails to generate the list of plugins to update 

## Expected Behaviour

The loader plugin shouldn't attempt to load modules or plugins and only report on the plugins which are required in the requested layers

## Possible Solution

Disable module loading when using the loader entrance or use a new input mode to disable module loading 

## Steps to Reproduce

1. Install v1.0.1 of this plugin  using hamlet setup 

```
            "cognitoqs" : {
                "Enabled" : true,
                "Name" : "cognitoqs",
                "Priority" : 200,
                "Required" : true,
                "Source" : "git",
                "Source:git" : {
                    "Url" : "https://github.com/hamlet-io/aws-cognito-quicksight-auth",
                    "Ref" : "v2.0.0",
                    "Path" : "hamlet/cognitoqs"
                }
            },
```

2. Update the plugin to v2.0.0 which changes the API definition loading from using addDefinition to loadModule using the definitions parameter
3. Run hamlet setup again to load the new version of the plugin 
4. creating the plugin contract will fail with the error that required the API definition loading failure 

```
master└─ $ hamlet --account envprd01 setup
(Info) Generating outputs:
(Info)  - generationcontract
(Fatal) ! template engine internal issue encountered. Details follow...

Apr 06, 2021 12:04:43 AM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> addDefinition  [in template "cognitoqs/modules/cognito_quicksight/module.ftl" at line 120, column 7]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

```

Without removing the plugin cache this means I can't move any further in using this solution

**Comment by ml019** [comment]
To load the plugin, it must have still thought it was using the previous version. I'll try and reproduce. There was a small tweak to the setup script to set a customer parameter for the loader entrance, but if that wasn't there, the error should have been about not being able to load the v2 plugin

**Comment by roleyfoley** [comment]
it found the existing plugin then tried to load the module. So this wasn't the plugin specfically but more that an older plugin was loaded and as a result its modules were invoked. 

The loader used to skip any module invocation which is probably the more ideal approach since it removes any potential issues like this
