### ISSUE TITLE
Lambda runtime validation relaxation

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#1640]
## Expected Behaviour
Hamlet should accept values for run-times when they are released by AWS.

## Current Behaviour
Hamlet developers must review and explicitly add new run-time values. While this ensures validation of values at template creation time, it imposes a maintenance burden and also means the use may enter a legitimate value as far as AWS is concerned but not supported as far as Hamlet is concerned. 

## Possible Solution
Remove values list and add a reference in the description of the attribute to the location in AWS of the current list.

## Context
Concern is this affects the first 30 minute experience of hamlet.

**Comment by roleyfoley** [comment]
From #1986 

> I'm wondering if we need an option to provide a value set and flag a warning rather than an error if the value provided is outside the set. That way we don't stop new values being used, but do assist when the value has a typo.
> 
> So basically extending the current logic that checks for values to check if say an `AdditionalValues : true` attribute is present and set to true. In this case, allow a user defined value but warn of its use. We can still perform other checks such as type conformance.
> 
> I'm reflecting the pattern used in JSON schema where `additionalProperties : true` controls whether unspecified properties can be present on an object.

Yeah I like it!
