### ISSUE TITLE
Consolidate scripts into a single "codeontap" command

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#166]
Provide a single command that allows access to all codeontap cli  functions. This is a precursor to dockerising codeontap (see #130) This script will become the default entrypoint.

It will provide switches for all the usual suspects (TENANT, PRODUCT, ENVIRONMENT, SEGMENT, TIER, COMPONENT, DEPLOYMENT_UNIT before checking for a verb and a noun. Subsequent switches will be specific to the verb/noun combination.

The command will try to find the root of the context tree and then work from there. When used in docker, the working directory will be indir, which is expected to be mapped as a volume to the root of the tree to be processed. We will add a marker fil in the image so that if indir isn't mapped, we can put out an error.

**Comment by RossMurr4y** [comment]
@ml019 are you happy to close this off, given we've now renamed to hamlet, containerised the product and introduced a CLI?

**Comment by ml019** [comment]
Yep - it has well and truly been superceded by events.
