### ISSUE TITLE
Link based image sourcing

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1689]
## Expected Behaviour

When configuring the source of an Image I can specify a link to another component of the same image type and the linked components image details will be used by the component

## Current Behaviour

We currently have this implemented through shared_build references where you can add a settings file to define this relationship. Allowing this in the solution would mean that the configuration can be applied using deployment profiles or instance version inheritance and reduce the settings files required to enable this. 

## Possible Solution

Add a new image source `link` and include a link based configuration option. When processing build information this would be used to find another component and use these details for build config 

## Context

This makes it easier to manage images and how they configured and aligns with our new image management process

**Comment by ml019** [comment]
While this sounds relatively easy to do, are we better doing it in conjunction with introducing a "code" component?

Maybe introudce the link idea (which is needed regardless) then add support later to linking to a "code" component,

**Comment by roleyfoley** [comment]
Both image component and link based image sources have been implemented in 
https://github.com/hamlet-io/engine/pull/2035
https://github.com/hamlet-io/engine-plugin-aws/pull/658
