### ISSUE TITLE
Support AWS Linux 2

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#171]
When it goes GA, 

* review/update the startup repo to accommodate both variants
* update templates to use Linux 2 for new builds, but leave existing ones as they are

**Comment by roleyfoley** [comment]
AWS Linux 2 is now GA and it looks like AWS have stopped publishing updated AMI images for aws linux 1 as of the 2018.03 release 

Happy to start looking into this

**Comment by roleyfoley** [comment]
One identified issue is using postgres 10 + on bastion hosts for database backups 
AWs linux no longer providers this as a part of the yum packages
