### ISSUE TITLE
[BUG] Occurrence handling across subcomponent types

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1726]
## Current Behaviour

When creating a component with two different subcomponents that have different types, if I use the same Id for the subcomponents only one is created as an occurrence 

## Expected Behaviour

As they are two independent components they should either raise an error that they don't have a unique id within the context of the component or have a way to distinguish between the different subcomponents 

## Steps to Reproduce

See: https://github.com/hamlet-io/engine/pull/1725#issuecomment-872765530

**Comment by ml019** [comment]
Fixed in https://github.com/hamlet-io/engine/pull/1725
