### ISSUE TITLE
[BUG] hamlet cli does not allow for creation of sesruleset due to deployment:Unit validation

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/engine#1857]
## Current Behaviour

hamlet cli expects the deployment unit for sesruleset to be ses (due to resourcesets). This means you can not create account sesruleset through hamlet cli

## Expected Behaviour

Either hamlet deploy *-deployments --district account should acknowledge sesruleset or the deployment unit of ses should include sesruleset. Note ManageAccount.sh does not have the check on deployment units and works as expected when passed sesruleset

## Steps to Reproduce

1. Go to account repo for any project with sesruleset defined
2. hamlet deploy list-deployments --district account (note it does not list sesruleset)
3. hamlet deploy create-deployments --district account -u ses.* (note it does not create either ses nor sesruleset)
4.

## Your Environment
* CMDB Version used: 
* Blueprint:

**Comment by roleyfoley** [comment]
Resource sets within the engine control what is visible as a deployment when you run list-deployments. If you need to add a new one you can do it yourself as part of your solution 

In the your solution file add the following 

```
{
    "DeploymentGroups": {
        "account": {
            "ResourceSets": {
                "sesruleset" : {
                    "deployment:Unit" : "sesruleset",
                    "deployment:Priority" : 100,
                    "GroupDeploymentUnit" : false
                },
            }
        }
}
```

That will add the resource set to the deployment group and make it available when the cli asks the engine for the unit list
