### ISSUE TITLE
[BUG] Kineses Firehose - Updating existing deployments failing

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#1863]
## Current Behaviour

When updating an existing kinesis firehose CloudFormation updates fail with the following error

```
    "ResourceId": "firehosestreamXelbXappXwaflog",
    "ResourceType": "AWS::KinesisFirehose::DeliveryStream",
    "Status": "UPDATE_FAILED",
    "Reason": "Resource handler returned message: \"Enabling or disabling Dynamic Partitioning is not supported at the moment (Service: Firehose, Status Code: 400, Request ID: cb954bf1-c983-b2ba-919b-c7ce0f7c100f, Extended Request ID: fhcoQ8uG8cawXA+QafoDw2osFHa4qa/nUhhRQ53ieR0AdidZzK/bolCL28q0QorxqqmX33QdkmElTurmcSuDfPRVwOCSF0Pf)\" (RequestToken: 623ea0eb-8bf2-a5f2-b71e-9eb5eab3dd7a, HandlerErrorCode: InvalidRequest)"
  },
  {
  ```

It appears that dyanmic Partitioning can only be enabled on initial creation and any further updates require recreation 

## Expected Behaviour

The setup of dynamic partitioning should allow for updates to existing resources

## Possible Solution

Make dynamic partitioning optional instead of always applied

**Comment by ken9ross** [comment]
The dynamic partitioning is not being set atm and is listed as being optional with no specified defaults. 

Would you like to explicitly set that as Enabled/Disabled within ExtendedS3DestinationConfiguration, or switching between S3DestinationConfiguration (which does not support dynamic partitioning) and ExtendedS3DestinationConfiguration if backups and lambda processing is not configured?
