### ISSUE TITLE
Backup Support

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#1917]
## Expected Behaviour
It should be possible to use backup capabilities provided by providers to support the backup approaches required by products.

## Current Behaviour
There is currently no support for configuring backup facilities within providers.

## Possible Solution
- add new component `backupstore` with `backupstoreregime` subcomponent
- store offers configuration of encryption keys and notifications whenever a backup to a store occurs
- `backupstoreregime` provides details of a set of rules to apply and what should be targetted by the regime
- a regime can have links to specific resources to back up
- a regime can define a tag that if placed on a resource, will cause it to be included in the regime
- a regime can define a set of tags on the component that must match the same tag on the backupstore
- if a component is linked to a regime (and supports centralised backups), it will have any tags defined by the regime added in order that it will be affected by the regime. 

For AWS, 
- use a prologue script to detect if the required services are enabled for backup, and if not, enable them.

## Context
- support backup requirements of customer projects
- simplify the process of maintaining backups regardless of the project solution

**Comment by roleyfoley** [comment]
Do we need the split between the two components? If you want to have two stores capturing backups from different locations you could 

- Use a deployment profile 
- If the store supports it have a replication rule or option on the store 

Most backup services follow a pull/discovery based process so saying that a store has these rules to pull data into itself, might align with backup processes and make it simpler to configure.

**Comment by ml019** [comment]
Closing. Basic implementation in place. Any additions can be handled as enhancements if required.
