### ISSUE TITLE
[BUG] Same named modules from different providers interfereing with each other

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#1922]
## Current Behaviour
Previously, a `baseline` module had been successfully added to a customer configuration using a customer specific provider identifier. With the introduction of a module of the same name in the AWS provider, the customer template generations are reporting an error.

## Expected Behaviour
Given that references to modules include the provider, same named modules shouldn't interfere with each other.

## Possible Solution
It looks like it is attempting to run the correct module macro based on the name but with the incorrect parameter set.

## Steps to Reproduce

1. Run a deployment for the modern slavery product using the unicycle version of hamlet
2. The following trace is generated
```
FreeMarker template error:
When calling macro "homeaffairs_module_baseline", required parameter "ResourceSets" (parameter #3) was not specified.

----
Tip: If the omission was deliberate, you may consider making the parameter optional in the macro by specifying a default value for it, like <#macro macroName paramName=defaultExpr>)
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #macro?with_args(...) homeaffairs_mod...  [in template "homeaffairs/modules/baseline/module.ftl" in macro "homeaffairs_module_baseline" at line 225, column 1]
        - Reached through: @(.vars[moduleMacro])?with_args(modul...  [in template "inputdata/seed.ftl" in macro "seedModuleData" at line 49, column 9]
        - Reached through: @seedModuleData provider=module.Provi...  [in template "shared/inputseeders/shared/id.ftl" in function "shared_configseeder_module" at line 542, column 13]
        - Reached through: @pushInputSource inputSource=inputSou...  [in template "inputdata/inputsource.ftl" in macro "initialiseInputProcessing" at line 22, column 5]
        - Reached through: @initialiseInputProcessing inputSourc...  [in template "bootstrap.ftl" at line 76, column 1]
        - Reached through: #include "/bootstrap.ftl"  [in template "invokeEntrance.ftl" at line 2, column 1]
```
3. Same occurs when using a local configuration
4. Now rename `aws/modules/baseline` and `aws/modules/baseline/modules.ftl` in the local configuration so they are not detected by the engine
4. Template generation now completes successfully

## Your Environment
* CMDB Version used: 
* Blueprint:

**Comment by roleyfoley** [comment]
This appears to be an issue in the configurationSet processing where the Provider is listed under the configuration rather than in the object structure. 

So will need to add a filter on the configuration set to provide only the one that matches the provider
