### ISSUE TITLE
[BUG] SubComponent (vs Port) not handled correctly for Ports under ECS

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/engine#1933]
## Current Behaviour
When adding
```
"Ports" : {
  "flask" : {
      "LB" : {
          "Tier" : "elb",
          "Component" : "apilb",
          "SubComponent" : "http"
      }
  }
}
```
To an ECS (Getting Started Load-Balancer point 3), results in an error of
```
"EffectiveLink": {
  "Id": "lb",
  "Name": "lb",
  "Tier": "elb",
  "Component": "apilb",
  "Enabled": true,
  "SubComponent": "flask",
  "Instance": "",
  "Version": ""
}
```
Replacing SubComponent with Port resolves the error

## Expected Behaviour
Either Port and SubComponent on ECS/Services/Ports should produce the same results
Or update the doco including Getting Started to use Port

## Steps to Reproduce

1. Follow Getting Started guide to Load-Balancer point 3

## Your Environment
* Occurs in both unicycle and tram releases 9 Feb 2022

**Comment by roleyfoley** [comment]
With #2000 This should now be fixed up.
