### ISSUE TITLE
Override Error responses from WAF

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#2016]
## Expected Behaviour

When a 5XX or 4XX error message is sent from an origin a generic error page is displayed to the user instead of the error pages presented by CloudFront/WAF or the backend server

## Current Behaviour

The response from the service that generated the HTTP response is returned

## Possible Solution

I think this is provided through here 
https://docs.aws.amazon.com/waf/latest/developerguide/customizing-the-response-for-blocked-requests.html 

## Context

The idea here is to attempt the information exposed to malicous users about the system that is denying access to the user

**Comment by ken9ross** [comment]
Useful code fragment - powershell configure custom error pages
```
Set-Location IIS:\Sites\MySite

add-WebConfiguration -Filter /System.WebServer/HttpErrors -Value @{StatusCode=403;SubStatusCode=4;PrefixLanguageFilePath="$Null";  Path="~/Content/ErrorMessages/403-4.html"; ResponseMode="ExecuteURL"}
```

**Comment by ken9ross** [comment]
@roleyfoley The default pattern on the IIS installation is that custom errors are rendered to remote calls (with the detailed error messages reserved for local calls). Given that I don't understand this ticket. 

We can forcibly reset the errorMode on any websites to address it, but the default would have had to be overwritten to cause the issue, so should we?

Do you have an example of the issue that you wish to block, so I can investigate how it got to that state (or if the definition of local is being broken somehow)?

**Comment by ken9ross** [comment]
@roleyfoley I thought you were picking this one up (using CloudFront instead). Did I misunderstand or is this just a dead ticket now?
