### ISSUE TITLE
Provide encryption at rest options for supported resources

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#669]
Encryption at rest is offered by cloud providers to offer a security layer between the data your are storing in the cloud provider and the cloud provider or other customers. 

A number of security policy frameworks,  PCI, IRAP/ISM etc require this to be enabled on any service which offers this. 

When encrypting the data the preference is to use a key that is owned by the customer which has either been created by the customer or the provider. Keys which are not owned by the customer should not be used where possible

**Comment by ml019** [comment]
Some support added for encryption at rest for existing components. No further action needed at this point
