### ISSUE TITLE
MultiAz configuration should apply at occurrence level

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#695]
At the moment the multiAz configuration stops at the component level rather than running off the occurrence configuration.

This means that the multiAz global variable is not defined in some cases ( blueprint generation) and can result in different result between the template and the blueprint

**Comment by ken9ross** [comment]
@roleyfoley I think this translates to

```
        "componentName": {
          "MultiAZ": true|false,
          "componentType": {
            "Instances": {
              "instanceName": {
                "MultiAZ": true|false,
                "Versions": {
                  "versionName": {
                    "MultiAZ": true|false,
                    "DeploymentUnits": [
                      "duName"
                    ]
```
That MultiAZ can be defined at any of the three levels above (currently only the first is supported). The most specific (applicable) definition will hold precedence. The value of MultiAZ will be defined at the occurrence level and all references to component.MultiAZ will need to change to occurrence.MultiAZ.

Have I understood it correctly?

**Comment by roleyfoley** [comment]
Yeah kinda. I think there are a couple of steps in this one 

1. Identify components that actually use MultiAZ - It doesn't make sense on all components
2. For the ones that do support MultiAZ add an Attribute to their standard component configuration. 
   - That component configuration has a few potential options for backwards compatibility 
      - true false ( the standard configuration option which will be used going forward ) 
      - _component _environment _product ( when these options are set then the appropriate MultiAZ value is used ). This might be better as an array as  I think thats how the default configuration works at the moment ). The array would be the current default configuration and you can easily override the configuration on the occurrence as you need to with new methods ( I.e. with deployment profiles and the like ) 

An attribute can have multiple types supported so it would be something like 

```
{
    "Names" : "MultiAZ",
    "Types" : [ BOOLEAN_TYPE, ARRAY_OF_STRING_TYPE ],
    "Values" : [ true, false, "_component", "_environment", "_product" ].
    "Default" : [ "_component". "_environment", "_product"
}
```

You would need to check on where the current multiAZ configuration comes from and what order it is evaluated in. What I've put is just a guess and haven't looked through the code.

**Comment by ken9ross** [comment]
The legacy values seem to be handled via a #assigned variable solnMultiAZ which is used as default on components in `component.MultiAZ!solnMultiAZ` constructs. My plan was to replace this with `occurrence.MultiAZ!solnMultiAZ`, where occurrence.MultiAZ is determined as above, meaning I can define MultiAZ as a "boolean, non-mandatory, without default" to avoid impacting on the existing legacy handling

**Comment by roleyfoley** [comment]
Added in https://github.com/hamlet-io/engine/pull/1969 

This was instead implemented as a breaking change and removes all support for layers defining MultiAZ Configuration. Instead deployment profiles can be used on layers to control the MultiAZ Property of component attributes.
