### ISSUE TITLE
Resource Groups

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#931]
Resource groups provide component designers with the ability to deploy resources within a given component to different placements #928 

This allows for scenarios where DNS records or Certificates are managed in a dedicated, consolidated DNS account to maintain separation between the DNS entires which essentially enable access to deployed component and the actual deployed components. 

The resource groups in a component would each have their own placement which links to an appropriate account/region/provider for that resource group. Because of this component designers should be careful when using resource groups to ensure that at component can be split where appropriate

**Comment by ml019** [comment]
Core support for resource groups (each with a placement) has been added to the engine. However, the placements are all currently identical. Allowing for different placements per resource groups is the subject of a separate issue.
