### ISSUE TITLE
Reference Generation Failing with dynamic loading

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#995]
When deploying the latest release of codeontap I found that the component reference markdown document only contains a couple of components, S3 and ec2.

This appears to be an issue with the new lazy loading technique for components since components only really exist when they are referenced in a deployment unit 

We need a way to either discover or specify ( ideally discover for maintainability ) the components available across all plugins in a given codeontap installation in order to generate a complete reference of the available configuration

**Comment by ml019** [comment]
Core support needed for this coming in https://github.com/codeontap/gen3-freemarker-wrapper/issues/16

**Comment by roleyfoley** [comment]
Implemented in https://github.com/hamlet-io/engine/pull/1364
